import "./globals.css";
import type { Metadata } from "next";
import { Footer, Header } from "./components/layout";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const albert = localFont({
  src:"./fonts/AlbertSans-Regular.ttf"
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {;
  return (
    <html lang="en">
      <body
        className={`${albert.className} antialiased print:w-full bg-neutral-900 `}
      >
      <Header/>
      <div className="sm:w-1/2 mx-auto sm:my-20 my-4 px-4">
        {children}
      </div>
      <Footer/>
      </body>
    </html>
  );
}
